name: RPGItems
main: think.rpgitems.Plugin
version: 3.6
dev-url: https://github.com/NyaaCat/RPGitems-reloaded
softdepend: [WorldGuard,NyaaCore]
commands:
    rpgitem:
        description: RPG Items
        usage: RPG Items

permissions:
    rpgitemupdate.command:
        default: op
    rpgitem.allowenchant.new:
        default: op
    rpgitem.allowenchant.old:
        default: op