name: RPGItems
main: think.rpgitems.Plugin
version: 3.5
dev-url: https://github.com/NyaaCat/RPGitems-reloaded
softdepend: [WorldGuard]
commands:
    rpgitem:
        description: RPG Items
        usage: RPG Items
