name: RPGItems
main: think.rpgitems.RPGItems
description: "RPGItems"
version: 3.6
depend: [NyaaCore]
softdepend: [WorldGuard]
authors: [RecursiveG,Librazy]
website: "https://github.com/NyaaCat/RPGitems-reloaded"
database: false

commands:
  rpgitem:
    description: RPG Items
    permission: rpgitem
    permission-message: "You do not have the required permission: <permission>"
    usage: "/<command> [SubCommand...] [Arguments...] or /<command> help"

permissions:
  rpgitem.allowenchant.new:
    default: op
  rpgitem.allowenchant.old:
    default: op